services:
  db:
    image: postgres:16
    container_name: nfl_pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql:/sql
      - ./data:/data
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    container_name: nfl_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
volumes:
  pgdata:
