name: CI (schema + views + QA)

on:
  push:
  pull_request:
  schedule:
    - cron: "0 13 * * 1"   # Mondays @ 13:00 UTC (adjust if you like)

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nfl
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres -d nfl"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - uses: actions/checkout@v4

      - name: Install psql client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres -d nfl && break
            sleep 2
          done

      - name: Apply schema
        run: |
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/schema/00_extensions.sql
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/schema/01_dimensions.sql
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/schema/02_games.sql
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/schema/03_plays.sql
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/migrations/04_add_off_def.sql
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/migrations/06_enhance_plays_metrics.sql
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/migrations/07_play_flags.sql

      - name: Seed tiny fixture (two plays)
        run: |
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/staging/00_create_staging.sql
          printf "season,week,gameday,home_team,away_team,posteam,defteam,quarter,down,distance,play_type,yards_gained,epa,success,first_down,pass,rush,play_action,pass_attempt,sack,qb_hit,punt,interception,fumble_lost,penalty,penalty_team,penalty_yards,yardline_100,touchdown,drive\n2023,1,2023-09-10,KC,PHI,KC,PHI,1,1,10,pass,12,0.5,TRUE,TRUE,TRUE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,,0,80,FALSE,1\n2023,1,2023-09-10,KC,PHI,PHI,KC,1,1,10,rush,7,0.2,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,,0,70,FALSE,1\n" > /tmp/mini.csv
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -c "\copy staging.pbp_raw FROM '/tmp/mini.csv' CSV HEADER"
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/etl/21_stage_to_core_offdef.sql
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/etl/22_stage_to_core_metrics.sql
          psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/migrations/08_backfill_play_flags_robust.sql

      - name: Create views
        run: |
          for f in sql/analysis/views/*.sql; do
            psql "postgresql://postgres:postgres@localhost:5432/nfl" -f "$f"
          done

      - name: Run QA checks
        run: psql "postgresql://postgres:postgres@localhost:5432/nfl" -f sql/analysis/qa/qa_checks.sql
